---
- name: Remedyforce webhook listener for Offboadring
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5098

  rules:
    - name: trigger playbook for CyberArk Offboadring
      condition: event.payload.task.summary is search("To remove local pruadmin / administrator id from CyberArk")
      action:
        run_workflow_template:
          name: "CyberArk Offboadring"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To move to Sync OU
      condition: event.payload.task.summary is search("To move to Sync OU")
      action:
        run_workflow_template:
          name: "backup task PROD"
          organization: "Default"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for DNS check
      condition: event.payload.task.summary is search("To perform SCCM Console")
      action:
        run_workflow_template:
          name: "DNS A Record Creation WorkFlow PROD"
          organization: "Default"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for free ip allocation
      condition: event.payload.task.summary is search("To delete from VmWare")
      action:
        run_job_template:
          name: "Free_Ip_Allocation_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for os config
      condition: event.payload.task.summary is search("Take the full backup and then remove server from backup configuration. Keep the retention as per Prudential Backup policy for decommission servers.")
      action:
        run_job_template:
          name: "Windows_Os_Config_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for SCCM
      condition: event.payload.task.summary is search("To remove the server from ePO")
      action:
        run_job_template:
          name: "SCCM_Onboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Forcepoint
      condition: event.payload.task.summary is search("To remove BMC")
      action:
        run_job_template:
          name: "Forcepoint_Onboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Crowdstrike
      condition: event.payload.task.summary is search("To mark the affected CI’s as decommissioned in CMDB")
      action:
        run_job_template:
          name: "Crowdstrike_Onboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Dynatrace
      condition: event.payload.task.summary is search("To remove the computer from Nessus / Qualys scan.")
      actions:
        - run_job_template:
            name: "Dynatrace_Installation_PROD"
            organization: "Prudential"
            job_args:
              inventory: "{{ event.payload.task.locationid }}"
              extra_vars:
                task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Discovery on boarding
      condition: event.payload.task.summary is search("To remove the affected CI’s in BMC Discovery tools")
      action:
        run_job_template:
          name: "Discovery_Onboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"
