---
- name: Remedyforce webhook listener for Offboadring
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6181

  rules:
    - name: trigger playbook for CyberArk Offboadring
      condition: event.payload.task.summary is search("Remove user from CyberArk")
      action:
        run_job_template:
          name: "CyberArk Offboardring_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To move to Sync OU
      condition: event.payload.task.summary is search("To move to Sync OU")
      action:
        run_job_template:
          name: "AD Offboarding_PROD" # Change it
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To perform SCCM Console
      condition: event.payload.task.summary is search("To perform SCCM Console")
      action:
        run_job_template:
          name: "SCCM Offboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To delete from VmWare
      condition: event.payload.task.summary is search("To delete from VmWare.")
      action:
        run_workflow_template:
          name: "offboarding VM - unix/wintel_PROD" # Change it
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Backup Removal
      condition: event.payload.task.summary is search("Backup Removal")
      action:
        run_workflow_template:
          name: "Offboarding backup workflow_PROD" # Change
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To remove the server from ePO
      condition: event.payload.task.summary is search("To delete from DNS.")
      action:
        run_job_template:
          name: "DNS A record Removal_PROD" #  Not Complete
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To remove BMC
      condition: event.payload.task.summary is search("To remove from Truesight")
      action:
        run_job_template:
          name: "BMC Monitoring Offboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for decommissioned in CMDB
      condition: event.payload.task.summary is search("To mark the affected CI’s as decommissioned in CMDB")
      action:
        run_job_template:
          name: "Remedy CMDB Offboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Satellite
      condition: event.payload.task.summary is search("Satellite Offboarding")
      actions:
        - run_job_template:
            name: "Satellite Offboarding Unix_PROD"
            organization: "Prudential"
            job_args:
              inventory: "{{ event.payload.task.locationid }}"
              extra_vars:
                task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Discovery on boarding
      condition: event.payload.task.summary is search("To remove the affected CI’s in BMC Discovery tools")
      action:
        run_job_template:
          name: "Discovery Offboarding_PROD"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"
