---
- name: Remedyforce webhook listener for Offboadring
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5181

  rules:
    - name: trigger playbook for CyberArk Offboadring
      condition: event.payload.task.summary is search("Remove user from CyberArk")
      action:
        run_workflow_template:
          name: "CyberArk Offboadring"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To move to Sync OU
      condition: event.payload.task.summary is search("To move to Sync OU")
      action:
        run_workflow_template:
          name: "backup task PROD" # Change it
          organization: "Default"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To perform SCCM Console
      condition: event.payload.task.summary is search("To perform SCCM Console")
      action:
        run_workflow_template:
          name: "SCCM Offboarding"
          organization: "Default"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To delete from VmWare
      condition: event.payload.task.summary is search("To delete from VmWare")
      action:
        run_job_template:
          name: "Free_Ip_Allocation_PROD" # Change it
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Backup Removal
      condition: event.payload.task.summary is search("Backup Removal")
      action:
        run_job_template:
          name: "Windows_Os_Config_PROD" # Change
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To remove the server from ePO
      condition: event.payload.task.summary is search("To remove the server from ePO")
      action:
        run_job_template:
          name: "Test" #  Whet needs to be done check on monday
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for To remove BMC
      condition: event.payload.task.summary is search("To remove BMC")
      action:
        run_job_template:
          name: "BMC Monitoring Offboarding"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for decommissioned in CMDB
      condition: event.payload.task.summary is search("To mark the affected CI’s as decommissioned in CMDB")
      action:
        run_job_template:
          name: "Remedy CMDB Offboarding"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Satellite
      condition: event.payload.task.summary is search("To remove host from satellite")
      actions:
        - run_job_template:
            name: "Satellite Offboarding Unix UAT"
            organization: "Prudential"
            job_args:
              inventory: "{{ event.payload.task.locationid }}"
              extra_vars:
                task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Discovery on boarding
      condition: event.payload.task.summary is search("To remove the affected CI’s in BMC Discovery tools")
      action:
        run_job_template:
          name: "Discovery Offboarding"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"
