
---
- name: Remedyforce webhook listener
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5023

  rules:
    - name: trigger playbook for test tickets
      condition: >-
                  (
                  (event.payload.task.queue == "REG-SO-SrOps-Automation")
                  and ("New server Build" in (event.payload.task.summary))
                  )
      action:
        run_job_template:
         name: "Poll_test_Aruna"
         organization: "Prudential"
         job_args:
          extra_vars:
            task_id: "{{ event.payload.task.id | default('') }}"
            task_queue: "{{ event.payload.task.queue | default('') }}"
            task_number: "{{ event.payload.task.number_field | default('') }}"
            task_description: "{{ event.payload.task.description | default('') }}"
            summary: "{{ event.payload.task.summary | default('') }}"
         


          
