
---
- name: Remedyforce webhook listener
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5023

  rules:
    - name: trigger playbook for test tickets
      condition: event.payload.task.queue == "REG-SO-SrOps-Automation"
      action:
       run_job_template:
         name: "Poll_test_Aruna"
         organization: "Prudential"
         job_args:
           extra_vars:
             task_id: "{{ event.payload.task.id }}"
             task_queue: "{{ event.payload.task.queue }}"
             task_number: "{{ event.payload.task.number_field }}"
        # Full description
             task_description: "{{ event.payload.task.description }}"
        # Convert colon-separated description into key-value pairs
             description_dict: >-
                {{
                   dict(
                    event.payload.task.description.split(':')[::2] |
                    zip(event.payload.task.description.split(':')[1::2])
                   )
                 }}


          
