
---
- name: Remedyforce webhook listener
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5023

  rules:
    - name: trigger playbook for test tickets
      condition: event.payload.task.summary is search("New server Build")

      action:
        run_job_template:
         name: "Poll_test_Aruna"
         organization: "Prudential"
         job_args:
          extra_vars:
            task_id: "constant"
            #task_queue: "{{ event.payload.task.queue | default('')|string  }}"
            #task_number: "{{ event.payload.task.number_field | default('')|string  }}"
            #task_description: "{{ event.payload.task.description | default('')|string  }}"
            #summary: "{{ event.payload.task.summary | default('')|string  }}"
         


          
