- name: Salesforce Event Listener
  hosts: localhost
  sources:
    - redhat.salesforce:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        security_token: "{{ security_token }}"
        login_url: "{{ login_url }}"
  rules:
    - name: On Account Created
      condition: true = true
      action:
        run_job_template:
          name: test_template_hostname
