---
- name: Remedyforce webhook listener for Offboadring
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5234

  rules:
    - name: Trigger Playbook for Windows/Unix shutdown
      condition: event.payload.task.summary is search("Server shutdown & decommission")
      action:
        run_workflow_template:
          name: "VM_shutdown_UAT"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"


    - name: Trigger Discovery scan shutdown
      condition: event.payload.task.summary is search("Request to remove the device from Discovery scan")
      action:
        run_workflow_template:
          name: "Discovery_Shutdown_UAT"
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for CMDB inactive status change
      condition: event.payload.task.summary is search("Request to change the status to Inactive in CMDB")
      action:
        run_job_template:
          name: "CMDB_Inactive_UAT" # Change it
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Monitoring
      condition: event.payload.task.summary is search("Monitoring")
      actions:
       - run_job_template:
          name: "Monitoring_Shutdown_UAT"
          organization: "Prudential"
          job_args:
           inventory: "{{ event.payload.task.locationid }}"
           extra_vars:
            task_number: "{{ event.payload.task.number_field }}"
       - run_workflow_template:
          name: "Dynatrace_Shutdown_UAT"
          organization: "Prudential"
          job_args:
           inventory: "{{ event.payload.task.locationid }}"
           extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

    - name: trigger playbook for Backup Disable
      condition: event.payload.task.summary is search("Request to stop the backup")
      action:
        run_job_template:
          name: "Backup_Disable_Shutdown" # Change
          organization: "Prudential"
          job_args:
            inventory: "{{ event.payload.task.locationid }}"
            extra_vars:
              task_number: "{{ event.payload.task.number_field }}"

      

  
