- name: Handle Remedyforce test ticket
  hosts: localhost
  gather_facts: false
  tasks:
    - name: display the ctask number and description 
      ansible.builtin.debug:
        msg: 
          - "Task ID: {{ task_id }}"
          - "Task Number: {{ task_number }}"
          #- "Queue: {{ task_queue }}"
          #- "Description: {{ task_description }}"
          #- "Summary : {{ summary }}"
